# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - Cmd

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: BatchScript@1
  inputs:
    filename: 'Run script "Run VSDevCmd.bat"'
    arguments: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VSDevCmd.bat'
    modifyEnvironment: true

- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: '$(Build.SourcesDirectory)'
    FodConnection: 'FoD-setenant-int'
    ReleaseOptions: '0'
    ReleaseId: 1249532
    EntitlementSelection: '1'
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'msbuild'
    BuildFile: 'webgoat.net.sln'
    PollingInterval: 0
    PolicyFailAction: '0'