# Sync defects at defined interval
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron:  '* 7,18 * * *'   
    
jobs:
  FoD-BugTracker-Utility:
    # Use the appropriate runner for building your source code.
    # TODO: Use a Windows runner for .NET projects that use msbuild. Additional changes to RUN commands will be required to switch to Windows syntax.
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Bug tracker utility has been successfully tested with 1.8, other versions may also work
      - name: Set up Java
        uses: actions/setup-java@v3               
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Set up Fortify Bug Tracker Utility
        uses: fortify/gha-setup-bugtracker-utility@v1
        with:
          version: 4.1

      - name: Perform JIRA upload    
        env:
          FBTU_FODBASEURL: https://ams.fortify.com/
          FBTU_FODTENANT: ${{ secrets.FOD_TENANT }}
          FBTU_FODUSERNAME: ${{ secrets.FOD_USER }}
          FBTU_FODPASSWORD: ${{ secrets.FOD_PAT }}
          FBTU_FODRELEASEID: 378019
          FBTU_JIRABASEURL: https://territorypresales.atlassian.net/
          FBTU_JIRAUSERNAME: ${{ secrets.JIRA_USER }}
          FBTU_JIRAPASSWORD: ${{ secrets.JIRA_TOKEN }}
          FBTU_JIRAPROJECTKEY: BugTracker_Utility
        run: java -jar "$FBTU_JAR" -configFile "$FBTU_DIR/FoDToJira.xml" -FoDBaseUrl "$FBTU_FODBASEURL" -FoDTenant "$FBTU_FODTENANT" -FoDUserName "$FBTU_FODUSERNAME" -FoDPassword "$FBTU_FODPASSWORD" -FoDReleaseId "$FBTU_FODRELEASEID" --JiraBaseUrl "$FBTU_JIRABASEURL" -JiraUserName "$FBTU_JIRAUSERNAME" -JiraPassword "$FBTU_JIRAPASSWORD" -JiraProjectKey "$FBTU_JIRAPROJECTKEY"
